# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Steve Milburn
email: scmilburn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog featuring content on any and all things to do with web development
  including node.js, react, javascript, databases, etc.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.stvmlbrn.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: stvmlbrn
github_username:  stvmlbrn
linkedin_username: steve-milburn

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
tag_page_layout: tagpage
tag_page_dir: tag
paginate: 5
